env = Environment()

root_dir = "../"
inc_dirs = [root_dir, root_dir + "inc/"]

src_files = ["yeti.cc", "logger.cc"]

env.Replace(CC = "clang", CXX = "clang++")
env.Append(CPPPATH = inc_dirs)
env.Append(CCFLAGS = ["-O3", "-std=c++11"])
env.Append(LINKFLAGS = ["-pthread"])

shared_lib = env.SharedLibrary(target = "yeti", source = src_files)
static_lib = env.StaticLibrary(target = "yeti", source = src_files)
